# Relaychain Configuration
relaychain:
  image: parity/polkadot:v0.9.25
  chain: rococo-local
  env:
    RUST_LOG: parachain::candidate-backing=trace
  flags:
    - --rpc-methods=unsafe
    - --execution=wasm
  nodes:
    - name: alice
      wsPort: 9944
      rpcPort: 9933
      port: 30333
      flags:
        - --force-authoring
      env:
        RUST_LOG: babe=debug
    - name: bob
    - name: charlie

# Parachain Configuration
parachains:
# Config for first parachain
- image: quay.io/darwinia-network/darwinia-parachain:v5.3.2-rc1
  chain: # this could be a string like `dev` or a config object
    base: pangolin-parachain-dev
  id: 2000 # override parachain id
  parachain: true # this is parachain, not parathread
  flags:
    - --rpc-methods=unsafe
    - --force-authoring
    - --execution=wasm
  relaychainFlags:
    - --execution=wasm
  volumePath: /darwinia/data
  env:
    RUST_LOG: sc_basic_authorship=trace
  nodes:
    - wsPort: 9947
      rpcPort: 9936
      port: 30336
    - flags:
      - --alice
    - flags:
      - --bob
    - flags:
      - --charlie