// This file is part of Darwinia.
//
// Copyright (C) 2018-2022 Darwinia Network
// SPDX-License-Identifier: GPL-3.0
//
// Darwinia is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Darwinia is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Darwinia. If not, see <https://www.gnu.org/licenses/>.

//! Autogenerated weights for from_substrate_issuing_test
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-03-20, STEPS: `100`, REPEAT: 10, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 128

// Executed Command:
// ./target/release/drml
// benchmark
// --chain
// dev
// --wasm-execution
// compiled
// --pallet
// from_substrate_issuing_test
// --execution
// wasm
// --extrinsic=*
// --steps
// 100
// --repeat
// 10
// --raw
// --heap-pages=4096
// --output=./frame/wormhole/xxx/s2s/src/weight.rs
// --template=./.maintain/frame-weight-template.hbs


#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for from_substrate_issuing_test.
pub trait WeightInfo {
	fn issue_from_remote() -> Weight;
	fn burn_and_remote_unlock() -> Weight;
	fn set_remote_backing_account() -> Weight;
	fn set_secure_limited_period() -> Weight;
	fn set_security_limitation_ring_amount() -> Weight;
}

/// Weights for from_substrate_issuing_test using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	// Storage: ParaChainIssuing RemoteBackingAccount (r:1 w:0)
	// Storage: ParaChainIssuing SecureLimitedRingAmount (r:1 w:0)
	// Storage: ParaChainIssuing SecureLimitedPeriod (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: Balances TotalIssuance (r:1 w:1)
	fn issue_from_remote() -> Weight {
		(172_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(9 as Weight))
			.saturating_add(T::DbWeight::get().writes(4 as Weight))
	}
	// Storage: System Account (r:3 w:3)
	// Storage: System Number (r:1 w:0)
	// Storage: Balances Locks (r:2 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: BridgePangoroMessages PalletOperatingMode (r:1 w:0)
	// Storage: BridgePangoroMessages OutboundLanes (r:1 w:1)
	// Storage: FeeMarket AssignedRelayers (r:1 w:0)
	// Storage: ParaChainIssuing TransactionInfos (r:1 w:1)
	// Storage: BridgePangoroMessages OutboundMessages (r:0 w:1)
	fn burn_and_remote_unlock() -> Weight {
		(424_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(13 as Weight))
			.saturating_add(T::DbWeight::get().writes(8 as Weight))
	}
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: ParaChainIssuing RemoteBackingAccount (r:0 w:1)
	fn set_remote_backing_account() -> Weight {
		(43_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(4 as Weight))
			.saturating_add(T::DbWeight::get().writes(3 as Weight))
	}
	// Storage: ParaChainIssuing SecureLimitedPeriod (r:0 w:1)
	fn set_secure_limited_period() -> Weight {
		(5_000_000 as Weight)
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
	// Storage: ParaChainIssuing SecureLimitedRingAmount (r:1 w:1)
	fn set_security_limitation_ring_amount() -> Weight {
		(15_000_000 as Weight)
			.saturating_add(T::DbWeight::get().reads(1 as Weight))
			.saturating_add(T::DbWeight::get().writes(1 as Weight))
	}
}

// For backwards compatibility and tests
impl WeightInfo for () {
	// Storage: ParaChainIssuing RemoteBackingAccount (r:1 w:0)
	// Storage: ParaChainIssuing SecureLimitedRingAmount (r:1 w:0)
	// Storage: ParaChainIssuing SecureLimitedPeriod (r:1 w:0)
	// Storage: System Account (r:1 w:1)
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: Balances TotalIssuance (r:1 w:1)
	fn issue_from_remote() -> Weight {
		(172_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(9 as Weight))
			.saturating_add(RocksDbWeight::get().writes(4 as Weight))
	}
	// Storage: System Account (r:3 w:3)
	// Storage: System Number (r:1 w:0)
	// Storage: Balances Locks (r:2 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: BridgePangoroMessages PalletOperatingMode (r:1 w:0)
	// Storage: BridgePangoroMessages OutboundLanes (r:1 w:1)
	// Storage: FeeMarket AssignedRelayers (r:1 w:0)
	// Storage: ParaChainIssuing TransactionInfos (r:1 w:1)
	// Storage: BridgePangoroMessages OutboundMessages (r:0 w:1)
	fn burn_and_remote_unlock() -> Weight {
		(424_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(13 as Weight))
			.saturating_add(RocksDbWeight::get().writes(8 as Weight))
	}
	// Storage: System Number (r:1 w:0)
	// Storage: System ExecutionPhase (r:1 w:0)
	// Storage: System EventCount (r:1 w:1)
	// Storage: System Events (r:1 w:1)
	// Storage: ParaChainIssuing RemoteBackingAccount (r:0 w:1)
	fn set_remote_backing_account() -> Weight {
		(43_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(4 as Weight))
			.saturating_add(RocksDbWeight::get().writes(3 as Weight))
	}
	// Storage: ParaChainIssuing SecureLimitedPeriod (r:0 w:1)
	fn set_secure_limited_period() -> Weight {
		(5_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
	// Storage: ParaChainIssuing SecureLimitedRingAmount (r:1 w:1)
	fn set_security_limitation_ring_amount() -> Weight {
		(15_000_000 as Weight)
			.saturating_add(RocksDbWeight::get().reads(1 as Weight))
			.saturating_add(RocksDbWeight::get().writes(1 as Weight))
	}
}
