name: Check pull request

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  RUST_TOOLCHAIN: nightly

jobs:
  check-package:
    name: Check package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ env.RUST_TOOLCHAIN }}

      - name: Lint
        run: cargo clippy --all -- -D warnings

      - name: Run tests
        run: cargo test
