name: TEST-CI

on:
  pull_request:



env:
  RUST_TOOLCHAIN: nightly


jobs:
  ##
  # Build page
  ##
  build-package:
    name: Build package
    runs-on: ubuntu-latest
    container:
      image: ubuntu:16.04
    steps:

      - name: Test generate
        run: |
          BASE_PATH=target/x86_64-unknown-linux-gnu/release
          mkdir -p ${BASE_PATH}
          echo '' > ${BASE_PATH}/darwinia-collator

      - name: Collect shared
        run: |
          apt update -y
          apt install -y tree bzip2 zstd

          mkdir -p shared/crab-parachain-runtime
          mkdir -p shared/darwinia-parachain-runtime
          
          tree

          tar cjSf shared/darwinia-collator-x86_64-linux-gnu.tar.bz2 \
            -C target/x86_64-unknown-linux-gnu/release \
            darwinia-collator
          tar cf shared/darwinia-collator-x86_64-linux-gnu.tar.zst \
            -C target/x86_64-unknown-linux-gnu/release \
            darwinia-collator -I pzstd


